version: '3.9'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - selenium

  selenium:
    image: selenium/standalone-chrome-debug:latest
    ports:
      - "4444:4444"
      - "5900:5900"

